import MantineHeader from './header';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout({ children, className }) {
  const links = [
    {
      label: 'Поиск Вакансий',
      link: '/'
    },
    {
      label: 'Избранное',
      link: '/favourites'
    }
  ];
  return (
    <div className={className}>
      <MantineHeader links={links}>Header pidor</MantineHeader>
      {children}
    </div>
  )
}
