import MantineHeader from './header';
import { createStyles } from '@mantine/core';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const useStyles = createStyles((theme) => ({
  root: {
    backgroundColor: '#F7F7F8',
    height: '100%',
  },
}));

export default function Layout({ children, className }) {
  const { classes } = useStyles();
  const links = [
    {
      label: 'Поиск Вакансий',
      link: '/'
    },
    {
      label: 'Избранное',
      link: '/favourites'
    }
  ];
  return (
    <div className={className}>
      <MantineHeader links={links}>Header pidor</MantineHeader>
      <div className={classes.root}>
        {children}
      </div>
    </div>
  )
}
